### ISSUE TITLE
Sunset Donation Feature

### ISSUE THREAD

**Issue by Rodrigo400** [prosperoa/RealTalkDiscordBot#19]
As a user, the donation feature has provided a numerous amount of negative responses. This feature proves to be obsolete, lack of appeal, and against RealTalkBot objectives. 

Gracefully sunset the donation feature.

**Comment by prosperoa** [comment]
1. It's not a feature, it's a message from the bot once again asking for your financial support
2. It can't be obsolete or against the objectives because the dev team has no defined purpose or road map, kind of like the last season of Game of Thrones
3. who this?
4. The best I can do is sunset my credit card on file if you're willing to replace it with yours

Closing as: ha gottem!

**Comment by Rodrigo400** [comment]
Thanks for quick response and looking into this! :)
